version: "3.9"

networks:
  default:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 3s
      timeout: 5s
      retries: 3

  api:
    container_name: fastapi
    build: ./backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:secretpass@db:5432/database
      REDIS_HOST: redis
    networks:
      - default

  react-app:
    container_name: react-app
    image: react-image:latest
    build: ./frontend
    volumes:
      - ./src:/app/src
    ports:
      - 3000:80
    networks:
      - default

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - /appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_HOST: redis
